from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Deployer container for deploying the aggregated logging solution
  io.k8s.display-name: Logging deployer
  io.openshift.tags: logging,elk,fluentd
  vendor: Red Hat
name: openshift3/logging-deployer
owners:
- dev@lists.openshift.redhat.com
repo:
  type: rpms
no_oit_comments: true
