---
from:
  image: rhel7:7-released
labels:
  io.k8s.description: CRI-O is an implementation of the Kubernetes CRI. It is a lightweight,
    OCI-compliant runtime that is native to kubernetes. CRI-O supports OCI container
    images and can pull from any container registry.
  io.k8s.display-name: CRI-O
  io.openshift.tags: cri-o system rhel7
name: openshift3/cri-o
owners: []
repo:
  type: rpms
