content:
  source:
    alias: ose
    path: images/recycler
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and is used
    to prepare persistent volumes for reuse after they are deleted.
  io.k8s.display-name: OpenShift Container Platform Volume Recycler
  io.openshift.tags: openshift,recycler
  vendor: Red Hat
name: openshift3/ose-recycler
owners: []
repo:
  type: rpms
