content:
  source:
    alias: ose
    path: images/deployer
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and executes
    the user deployment process to roll out new containers. It may be used as a base
    image for building your own custom deployer image.
  io.k8s.display-name: OpenShift Container Platform Deployer
  io.openshift.tags: openshift,deployer
  vendor: Red Hat
name: openshift3/ose-deployer
owners: []
