from:
  image: jboss-eap-7/eap70-openshift:1.5
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Metric handling engine in OpenShift
  io.k8s.display-name: Hawkular Metrics
  io.openshift.tags: metrics,hawkular,hawkular-metrics
  vendor: Red Hat
name: openshift3/metrics-hawkular-metrics
owners: []
repo:
  type: rpms
