content:
  source:
    alias: online
    path: accountant
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  vendor: Red Hat
name: openshift3/oso-accountant
owners: []
repo:
  type: rpms
enabled_repos:
    - rhel-server-ose-rpms
    - rhel-server-optional-rpms