content:
  source:
    alias: ose
    path: images/router/haproxy
    # Replacement to fix mysterious osbs repo containing of haproxy RPM: cbs-paas7-openshift-multiarch-el7-build
    modifications:
    - action: replace
      match: yum install
      replacement: yum --disablerepo='cbs-paas7-openshift-multiarch-el7-build' install
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and contains
    an HAProxy instance that automatically exposes services within the cluster through
    routes, and offers TLS termination, reencryption, or SNI-passthrough on ports
    80 and 443.
  io.k8s.display-name: OpenShift Container Platform HAProxy Router
  io.openshift.tags: openshift,router,haproxy
  vendor: Red Hat
name: openshift3/ose-haproxy-router
owners: []
