content:
  source:
    alias: descheduler
    path: images/descheduler

from:
  stream: rhel

labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Descheduler for Opensift and Kubernetes
  io.k8s.display-name: Descheduler
  io.openshift.tags: openshift,descheduler
  vendor: Red Hat

name: openshift3/descheduler
owners: []

repo:
  type: rpms

enabled_repos:
    - rhel-server-ose-rpms

