---
# populated from branch: rhaos-3.6-rhel-7
from:
  image: rhel7:7.3-released
labels:
  io.k8s.description: AWS EFS dynamic PV provisioner
  io.k8s.display-name: EFS Provisioner
  io.openshift.tags: aws,efs,dynamic,provisioner
name: openshift3/efs-provisioner
owners: []
repo:
  type: rpms
  branch: rhaos-3.6-rhel-7