from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Curator elasticsearch container for elasticsearch deletion/archival
  io.k8s.display-name: Curator 3.5.0-2
  io.openshift.tags: logging,elk,elasticsearch,curator
  vendor: Red Hat
name: openshift3/logging-curator
repo:
  type: rpms
no_oit_comments: true
enabled_repos:
    - rhel-server-ose-rpms
    - rhel-server-extras-rpms
