from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Heapster image for metrics collection.
  io.k8s.display-name: Heapster
  io.openshift.tags: metrics,heapster
  vendor: Red Hat
name: openshift3/metrics-heapster
repo:
  type: rpms
enabled_repos:
    - rhel-server-ose-rpms
