content:
  source:
    alias: ose
    modifications:
    - action: replace
      match: origin-sdn-ovs
      replacement: atomic-openshift-sdn-ovs
    path: images/node
enabled_repos:
- rhel-server-ose-rpms
- rhel-fast-datapath-rpms
- rhel-server-extras-rpms
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and contains
    the software for individual nodes when using SDN.
  io.k8s.display-name: OpenShift Container Platform Node
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift3/node
owners: []
