from:
  stream: rhel

content:
  source:
    alias: cri-o
    path: contrib/system_containers/rhel

labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: CRI-O is an implementation of the Kubernetes CRI. It is a lightweight, OCI-compliant runtime that is native to kubernetes. CRI-O supports OCI container images and can pull from any container registry.
  io.k8s.display-name: CRI-O
  vendor: Red Hat

name: openshift3/cri-o

owners: []

repo:
  type: rpms

enabled_repos:
- rhel-server-ose-rpms
- rhel-server-extras-rpms
