from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and runs
    Service Catalog.
  io.k8s.display-name: OpenShift Container Platform Service Catalog
  io.openshift.tags: openshift,service-catalog
  vendor: Red Hat
name: openshift3/ose-service-catalog
owners: []
repo:
  type: rpms
