content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/configmap-reload.git
      web: https://github.com/openshift/configmap-reload
    path: ''
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: configmap-reload-container
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
labels:
  License: ASL 2.0
  io.k8s.description: This is a component reloads another process if a configured
    configmap volume is remounted.
  io.k8s.display-name: configmap reload
  io.openshift.tags: kubernetes
  vendor: Red Hat
name: openshift/ose-configmap-reloader-rhel9
payload_name: configmap-reloader
owners:
- team-monitoring@redhat.com
