content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/configmap-reload.git
    path: ''
container_yaml:
  go:
    modules:
    - module: github.com/jimmidyson/configmap-reload
enabled_repos:
- rhel-server-rpms
- rhel-server-optional-rpms
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This is a component reloads another process if a configured
    configmap volume is remounted.
  io.k8s.display-name: configmap reload
  io.openshift.tags: kubernetes
  vendor: Red Hat
name: openshift/ose-configmap-reloader
owners:
- team-monitoring@redhat.com
