content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/configmap-reload.git
    path: ''
container_yaml:
  go:
    modules:
    - module: github.com/jimmidyson/configmap-reload
from:
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This is a component reloads another process if a configured
    configmap volume is remounted.
  io.k8s.display-name: configmap reload
  io.openshift.tags: kubernetes
  vendor: Red Hat
name: openshift3/ose-configmap-reloader
owners:
- fbranczy@redhat.com
