content:
  source:
    dockerfile: Dockerfile.rhel
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus.git
enabled_repos:
- rhel-server-ose-rpms
from:
  builder:
  - stream: golang
  stream: rhel
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus
required: true
