content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/node_exporter.git
      web: https://github.com/openshift/node_exporter
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: golang-github-prometheus-node_exporter-container
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
- rhel-9-server-ose-rpms-embargoed
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
labels:
  License: ASL 2.0
  io.k8s.description: Prometheus exporter for hardware and OS metrics exposed by *NIX
    kernels, written in Go with pluggable metric collectors
  io.k8s.display-name: Node Exporter
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift/ose-prometheus-node-exporter-rhel9
payload_name: prometheus-node-exporter
non_shipping_repos:
- rhel-9-server-ose-rpms-embargoed
owners:
- team-monitoring@redhat.com
alternative_upstream:
- when: el8
  distgit:
    branch: rhaos-{MAJOR}.{MINOR}-rhel-8
    component: golang-github-prometheus-node_exporter-container
  enabled_repos:
  - rhel-8-baseos-rpms
  - rhel-8-appstream-rpms
  - rhel-8-server-ose-rpms-embargoed
  from:
    builder:
    - stream: golang
    member: openshift-base-rhel8
  name: openshift/ose-prometheus-node-exporter
  non_shipping_repos:
  - rhel-8-server-ose-rpms-embargoed
