content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-alertmanager.git
      web: https://github.com/openshift/prometheus-alertmanager
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
  component: golang-github-prometheus-alertmanager-container
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
- rhel-8-server-ose-rpms-embargoed
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-base-rhel8
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus Alert Manager image.
  io.k8s.display-name: Prometheus Alert Manager
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-alertmanager
payload_name: prometheus-alertmanager
non_shipping_repos:
- rhel-8-server-ose-rpms-embargoed
owners:
- team-monitoring@redhat.com
external_scanners:
  sast_scanning:
    jira_integration:
      enabled: true
