container_yaml:
  go:
    modules:
    - module: github.com/openshift/prometheus
content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus.git
enabled_repos:
- rhel-server-rpms
- rhel-server-ose-rpms-embargoed  # required by the builder
non_shipping_repos:
- rhel-server-ose-rpms-embargoed
from:
  builder:
  - stream: golang
  stream: rhel
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus
owners:
- team-monitoring@redhat.com
