content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus.git
enabled_repos:
- rhel-server-ose-rpms
from:
  stream: rhel
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift3/prometheus
