container_yaml:
  go:
    modules:
    - module: github.com/openshift/prometheus-alertmanager
content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-alertmanager.git
enabled_repos:
- rhel-server-rpms
- rhel-server-ose-rpms  # required by the builder
non_shipping_repos:
- rhel-server-ose-rpms
from:
  builder:
  - stream: golang
  stream: rhel
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus Alert Manager image.
  io.k8s.display-name: Prometheus Alert Manager
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-alertmanager
owners:
- team-monitoring@redhat.com
