container_yaml:
  go:
    modules:
    - module: github.com/openshift/prometheus
content:
  source:
    dockerfile: Dockerfile.rhel
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus.git
enabled_repos:
- rhel-server-ose-rpms
- rhel-server-ose-rpms-shipped
from:
  builder:
  - stream: golang-1.12
  stream: rhel
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus
owners:
- team-monitoring@redhat.com
