content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus.git
      web: https://github.com/openshift/prometheus
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
- rhel-8-server-ose-rpms-embargoed
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-base-rhel8
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus
non_shipping_repos:
- rhel-8-server-ose-rpms-embargoed
owners:
- team-monitoring@redhat.com
comet:
- type: repository
  name: openshift4/ose-prometheus
  id: 5cdc1e585a13467289f5841a
