content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus.git
      web: https://github.com/openshift/prometheus
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: golang-github-prometheus-prometheus-container
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
- rhel-9-server-ose-rpms-embargoed
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-rhel9
payload_name: prometheus
non_shipping_repos:
- rhel-9-server-ose-rpms-embargoed
owners:
- team-monitoring@redhat.com
