content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus-alertmanager.git
enabled_repos:
- rhel-server-ose-rpms
- rhel-server-ose-rpms-shipped
from:
  stream: rhel
image_build_method: docker_api
labels:
  License: ASL 2.0
  io.k8s.description: This is the Prometheus Alert Manager image.
  io.k8s.display-name: Prometheus Alert Manager
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift3/prometheus-alertmanager
