content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/node_exporter.git
    modifications:
    - action: add
      source: https://gitlab.cee.redhat.com/aosqe/ocp-build-data-gating/raw/master/openshift-{MAJOR}.{MINOR}/golang-github-prometheus-node_exporter/gating_yaml
      path: gating.yaml
      overwriting: true
enabled_repos:
- rhel-server-ose-rpms
from:
  stream: rhel
image_build_method: docker_api
labels:
  License: ASL 2.0
  io.k8s.description: Prometheus exporter for hardware and OS metrics exposed by *NIX
    kernels, written in Go with pluggable metric collectors
  io.k8s.display-name: Node Exporter
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift3/prometheus-node-exporter
owners: []
