name: openshift3/prometheus-alert-buffer

enabled_repos:
- rhel-server-ose-rpms
- rhel-server-ose-rpms-shipped

from:
  stream: rhel

image_build_method: docker_api

labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is the Prometheus Alert Buffer image.
  io.k8s.display-name: Prometheus Alert Buffer
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
