container_yaml:
  go:
    modules:
    - module: github.com/openshift/node_exporter
content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/node_exporter.git
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
- rhel-8-server-ose-rpms
for_payload: true
from:
  builder:
  - stream: golang
  stream: rhel
labels:
  License: ASL 2.0
  io.k8s.description: Prometheus exporter for hardware and OS metrics exposed by *NIX
    kernels, written in Go with pluggable metric collectors
  io.k8s.display-name: Node Exporter
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift/ose-prometheus-node-exporter
non_shipping_repos:
- rhel-8-server-ose-rpms
owners:
- team-monitoring@redhat.com
