content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/node_exporter.git
      web: https://github.com/openshift/node_exporter
enabled_repos:
- rhel-server-optional-rpms
- rhel-server-ose-rpms-embargoed
from:
  member: openshift-base-rhel7
labels:
  License: ASL 2.0
  io.k8s.description: Prometheus exporter for hardware and OS metrics exposed by *NIX
    kernels, written in Go with pluggable metric collectors
  io.k8s.display-name: Node Exporter
  io.openshift.tags: openshift,node
  vendor: Red Hat
name: openshift3/prometheus-node-exporter
owners: []
non_shipping_repos:
- rhel-server-optional-rpms
- rhel-server-ose-rpms-embargoed
