content:
  source:
    dockerfile: Dockerfile.openshift
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/ingress-node-firewall.git
      web: https://github.com/openshift/ingress-node-firewall
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
distgit:
  component: ingress-node-firewall-operator-container
  bundle_component: ingress-node-firewall-operator-bundle-container
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: false
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ingress-node-firewall-rhel8-operator
name_in_bundle: ingress-node-firewall
owners:
- mmahmoud@redhat.com
update-csv:
  bundle-dir: stable/
  manifests-dir: manifests/
  registry: image-registry.openshift-image-registry.svc:5000
  valid-subscription-label: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
