# [asdas] Disabling until upstream adds 4.15 configs to stable dir
mode: disabled
content:
  source:
    dockerfile: Dockerfile.openshift
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/ingress-node-firewall.git
      web: https://github.com/openshift/ingress-node-firewall
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  bundle_component: ingress-node-firewall-operator-bundle-container
  component: ingress-node-firewall-operator-container
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
for_payload: false
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ingress-node-firewall-rhel9-operator
name_in_bundle: ingress-node-firewall
owners:
- mmahmoud@redhat.com
update-csv:
  bundle-dir: stable/
  manifests-dir: manifests/
  registry: image-registry.openshift-image-registry.svc:5000
  valid-subscription-label: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
