content:
  source:
    dockerfile: Dockerfile.daemon.openshift
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/ingress-node-firewall.git
      web: https://github.com/openshift/ingress-node-firewall
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
distgit:
  component: ingress-node-firewall-daemon-container
dependents:
- ingress-node-firewall-operator
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: false
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ingress-node-firewall
name_in_bundle: ingress-node-firewall-daemon
owners:
- mmahmoud@redhat.com
