from:
  member: openshift-enterprise
labels:
  License: GPLv2+
  io.k8s.description: Deployer container for deploying the aggregated logging solution
  io.k8s.display-name: Logging deployer
  io.openshift.tags: logging,elk,fluentd
  vendor: Red Hat
name: openshift3/logging-deployer
owners: []
