content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/k8s-prometheus-adapter.git
      web: https://github.com/openshift/k8s-prometheus-adapter
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-k8s-prometheus-adapter
payload_name: k8s-prometheus-adapter
owners:
- team-monitoring@redhat.com
