content:
  source:
    dockerfile: Dockerfile.rhel7
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cluster-config-operator.git
      web: https://github.com/openshift/cluster-config-operator
    ci_alignment:
      streams_prs:
        commit_prefix: "UPSTREAM: <carry>: "
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: ose-cluster-config-operator-container
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-cluster-config-rhel9-operator
payload_name: cluster-config-operator
owners:
- aos-master@redhat.com
- tnozicka@redhat.com
canonical_builders_from_upstream: False # upstream is on rhel8, so disabling to prevent regression
