content:
  source:
    dockerfile: Dockerfile.setup-etcd-environment.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/machine-config-operator.git
from:
  builder:
  - image: openshift/golang-builder:1.10
  member: openshift-enterprise-base
name: openshift/ose-setup-etcd-environment
owners:
- acrawfor@redhat.com
- imcleod@redhat.com

