container_yaml:
  go:
    modules:
    - module: github.com/openshift/cluster-ingress-operator
content:
  source:
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cluster-ingress-operator.git
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-ingress-operator
owners:
- aos-network-edge@redhat.com
