content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cloud-network-config-controller.git
      web: https://github.com/openshift/cloud-network-config-controller
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
  component: ose-cloud-network-config-controller-container
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cloud-network-config-controller
payload_name: cloud-network-config-controller
owners:
- aos-networking-staff@redhat.com
external_scanners:
  sast_scanning:
    jira_integration:
      enabled: true
