container_yaml:
  go:
    modules:
    - module: github.com/directxman12/k8s-prometheus-adapter
content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/k8s-prometheus-adapter.git
enabled_repos:
- rhel-server-rpms
- rhel-server-optional-rpms
from:
  builder:
  - stream: golang-1.11
  member: openshift-enterprise-base
name: openshift/ose-k8s-prometheus-adapter
owners:
- team-monitoring@redhat.com
