mode: wip
container_yaml:
  go:
    modules:
    - module: github.com/openshift/cloud-network-config-controller
content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cloud-network-config-controller.git
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
maintainer:
  component: Networking
name: openshift/ose-cloud-network-config-controller
owners:
- aos-networking-staff@redhat.com
