content:
  source:
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/cluster-ingress-operator.git
from:
  builder:
  - image: openshift/golang-builder:1.10
  member: openshift-enterprise-base
name: openshift/ose-cluster-ingress-operator
owners:
- dev@lists.openshift.redhat.com
- aos-network-edge@redhat.com
