content:
  source:
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cluster-ingress-operator.git
      web: https://github.com/openshift/cluster-ingress-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          member: ci-openshift-build-root-latest.rhel9
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: ose-cluster-ingress-operator-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: ose-cluster-ingress-operator
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-cluster-ingress-rhel9-operator
payload_name: cluster-ingress-operator
owners:
- aos-network-edge@redhat.com
