content:
  source:
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cluster-ingress-operator.git
      web: https://github.com/openshift/cluster-ingress-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
  component: ose-cluster-ingress-operator-container
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cluster-ingress-operator
payload_name: cluster-ingress-operator
owners:
- aos-network-edge@redhat.com
external_scanners:
  sast_scanning:
    jira_integration:
      enabled: true
