content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/k8s-prometheus-adapter.git
      web: https://github.com/openshift/k8s-prometheus-adapter
    ci_alignment:
      streams_prs:
        auto_label:
        - approved
        - backport-risk-assessed
        - bugzilla/valid-bug
        - cherry-pick-approved
        - lgtm
        - staff-eng-approved
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: ose-prometheus-adapter-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: ose-k8s-prometheus-adapter
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-k8s-prometheus-adapter-rhel9
payload_name: k8s-prometheus-adapter
owners:
- team-monitoring@redhat.com
