content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/cloud-network-config-controller.git
      web: https://github.com/openshift/cloud-network-config-controller
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-cloud-network-config-controller
owners:
- aos-networking-staff@redhat.com
comet:
- type: repository
  name: openshift4/cloud-network-config-controller-rhel8
  id: 602ba351af687e60dd2a0c4e
