content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/api.git
      web: https://github.com/openshift/api
    ci_alignment:
      streams_prs:
        ci_build_root:
          member: ci-openshift-build-root-latest.rhel9
    okd_alignment:
      run_if_changed: '^Dockerfile\.ocp$|^Makefile$|^(manifests/.*|payload-command/.*|payload-manifests/.*)$'
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: ose-cluster-config-api-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: ose-cluster-config-api
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
name: openshift/ose-cluster-config-api-rhel9
payload_name: cluster-config-api
owners:
- jspeed@redhat.com
- deads@redhat.com
