container_yaml:
  go:
    modules:
    - module: github.com/directxman12/k8s-prometheus-adapter
content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/k8s-prometheus-adapter.git
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-k8s-prometheus-adapter
owners:
- fbranczy@redhat.com
- surbania@redhat.com
required: true
