content:
  source:
    dockerfile: Dockerfile.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-operator.git
      web: https://github.com/openshift/prometheus-operator
    path: ''
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-9-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: prometheus-operator-container
enabled_repos:
- rhel-9-baseos-rpms
- rhel-9-appstream-rpms
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
labels:
  License: ASL 2.0
  io.k8s.description: This component manages the lifecycle and configuration of a
    Prometheus monitoring server as well as Prometheus Alertmanager clusters.
  io.k8s.display-name: Prometheus Operator
  io.openshift.tags: prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-rhel9-operator
payload_name: prometheus-operator
owners:
- team-monitoring@redhat.com
external_scanners:
  sast_scanning:
    jira_integration:
      enabled: true
