content:
  source:
    dockerfile: Dockerfile.config-reloader.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus-operator.git
container_yaml:
  go:
    modules:
    - module: github.com/coreos/prometheus-operator
enabled_repos:
- rhel-server-rpms
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This component reloads a Prometheus server in a controlled and
    configurable way.
  io.k8s.display-name: Prometheus config reloader
  io.openshift.tags: prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-config-reloader
owners:
- team-monitoring@redhat.com
