content:
  source:
    dockerfile: Dockerfile.config-reloader.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-operator.git
      web: https://github.com/openshift/prometheus-operator
    ci_alignment:
      streams_prs:
        auto_label:
        - approved
        - backport-risk-assessed
        - bugzilla/valid-bug
        - cherry-pick-approved
        - lgtm
        - staff-eng-approved
        ci_build_root:
          member: ci-openshift-build-root-latest.rhel9
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: prometheus-config-reloader-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: ose-prometheus-config-reloader
for_payload: true
from:
  builder:
  - stream: rhel-9-golang
  member: openshift-enterprise-base-rhel9
labels:
  License: ASL 2.0
  io.k8s.description: This component reloads a Prometheus server in a controlled and configurable way.
  io.k8s.display-name: Prometheus config reloader
  io.openshift.tags: prometheus
name: openshift/ose-prometheus-config-reloader-rhel9
payload_name: prometheus-config-reloader
owners:
- team-monitoring@redhat.com
