content:
  source:
    dockerfile: Dockerfile
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/prometheus-operator.git
    path: ''
from:
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This component manages the lifecycle and configuration of a
    Prometheus monitoring server as well as Prometheus Alertmanager clusters.
  io.k8s.display-name: Prometheus Operator
  io.openshift.tags: prometheus
  vendor: Red Hat
name: openshift3/ose-prometheus-operator
owners:
- fbranczy@redhat.com
