content:
  source:
    dockerfile: Dockerfile.config-reloader.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/prometheus-operator.git
      web: https://github.com/openshift/prometheus-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-8
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: true
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
labels:
  License: ASL 2.0
  io.k8s.description: This component reloads a Prometheus server in a controlled and
    configurable way.
  io.k8s.display-name: Prometheus config reloader
  io.openshift.tags: prometheus
  vendor: Red Hat
name: openshift/ose-prometheus-config-reloader
payload_name: prometheus-config-reloader
owners:
- team-monitoring@redhat.com
