arches:
- x86_64
- aarch64
- ppc64le
content:
  source:
    dockerfile: Dockerfile.sriov-network-config-daemon.ocp
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/sriov-network-operator.git
      web: https://github.com/openshift/sriov-network-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          member: ci-openshift-build-root-latest.rhel9
dependents:
- sriov-network-operator
distgit:
  branch: rhaos-{MAJOR}.{MINOR}-rhel-9
  component: sriov-network-config-daemon-container
delivery:
  # Maps to honeybadger repo_name
  repo_name: ose-sriov-network-config-daemon
  delivery_repo_names:
  - openshift4/ose-sriov-network-config-daemon-rhel9
enabled_repos:
- rhel-9-minimal-baseos-rpms
- rhel-9-minimal-appstream-rpms
for_payload: false
from:
  builder:
  - stream: rhel-9-golang-1.25
  member: openshift-enterprise-base-rhel9-minimal
name: openshift/ose-sriov-network-config-daemon-rhel9
name_in_bundle: sriov-network-config-daemon
owners:
- multus-dev@redhat.com
