arches:
- x86_64
- aarch64
- ppc64le
content:
  source:
    dockerfile: Dockerfile.sriov-network-config-daemon.rhel7
    git:
      branch:
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift-priv/sriov-network-operator.git
      web: https://github.com/openshift/sriov-network-operator
    ci_alignment:
      streams_prs:
        ci_build_root:
          stream: rhel-8-golang-ci-build-root
dependents:
- sriov-network-operator
enabled_repos:
- rhel-8-baseos-rpms
- rhel-8-appstream-rpms
for_payload: false
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-sriov-network-config-daemon
owners:
- multus-dev@redhat.com
comet:
- type: repository
  name: openshift4/ose-sriov-network-config-daemon
  id: 5d97c4cad70cc50ebeab11cc
