container_yaml:
  go:
    modules:
    - module: github.com/openshift/sriov-network-config-daemon
content:
  source:
    dockerfile: Dockerfile.sriov-network-config-daemon.rhel7
    git:
      branch:
        fallback: master
        target: release-{MAJOR}.{MINOR}
      url: git@github.com:openshift/sriov-network-operator.git
enabled_repos:
- rhel-server-rpms
- rhel-server-optional-rpms
from:
  builder:
  - stream: golang
  member: openshift-enterprise-base
name: openshift/ose-sriov-network-config-daemon
owners:
- multus-dev@redhat.com
