from:
  image: rhscl/nodejs-6-rhel7
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: Kibana container for querying Elasticsearch for aggregated logs
  io.k8s.display-name: Kibana
  io.openshift.tags: logging,elk,kibana
  vendor: Red Hat
name: openshift3/logging-kibana
repo:
  type: rpms
