enabled_repos:
- rhel-server-ose-rpms
from:
  stream: rhel
labels:
  License: GPLv2+
  io.k8s.description: This is the Prometheus Alert Manager image.
  io.k8s.display-name: Prometheus Alert Manager
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift3/prometheus-alertmanager
