enabled_repos:
- rhel-server-ose-rpms
from:
  stream: rhel
# use standard build or this build runs into https://github.com/openshift/imagebuilder/issues/87
image_build_method: docker_api
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is the Prometheus Alert Buffer image.
  io.k8s.display-name: Prometheus Alert Buffer
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift3/prometheus-alert-buffer
