content:
  source:
    alias: prometheus
    dockerfile: Dockerfile.rhel7
enabled_repos:
- rhel-server-ose-rpms
from:
  stream: rhel
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is the Prometheus base image.
  io.k8s.display-name: Prometheus
  io.openshift.tags: openshift,prometheus
  vendor: Red Hat
name: openshift3/prometheus
