content:
  source:
    alias: ose
    path: images/router/f5
from:
  member: openshift-enterprise-docker
labels:
  License: GPLv2+
  architecture: x86_64
  io.k8s.description: This is a component of OpenShift Container Platform and programs
    a BigIP F5 router to expose services within the cluster.
  io.k8s.display-name: OpenShift Container Platform F5 Router
  io.openshift.tags: openshift,router,f5
  vendor: Red Hat
name: openshift3/ose-f5-router
owners: []
repo:
  type: rpms
