name: Run ocp-build-data-validator

on:
  pull_request:
    branches:
      - "openshift-**"
    paths:
      - "**.yml"
      - "rpms/**.yml"
      - "images/**.yml"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Clone art-tools
        run: |
          git clone https://github.com/openshift-eng/art-tools

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.18"
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Install validator
        run: |
          cd art-tools
          ./install.sh

      - name: Get all relevant files that have changed
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            config:
              - 'streams.yml'
              - 'group.yml'
              - 'releases.yml'
              - 'bug.yml'
              - 'rpms/**.yml'
              - 'images/**.yml'

      - name: Run validator

        if: steps.changed-files.outputs.config_any_changed == 'true'
        run: |
          uv run --project ./art-tools validate-ocp-build-data --exclude-vpn \
          --images-dir images ${{ steps.changed-files.outputs.config_all_changed_files }}
